name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Storage
      uses: azure/storage-blob-deploy@v2
      with:
        container_name: newcontainer
        source: folder_to_upload
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}


#    - name: Deploy to Azure Storage
#      uses: azure/storage-blob-deploy@v2
#      with:
#        source_path: path/to/folder
#        destination_path: mycontainer
#        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
