name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Azure Blob Upload with Destination folder defined
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container_name: newcontainer
        source_folder: folder_to_upload
        destination_folder: mmgresults
        clean_destination_folder: true
