name: testing_

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Running without schedule
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"