name: testing_

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Running without schedule
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"