name: testing_

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Running .py with schedule
        if: github.event.schedule != '30 5 * * 1,4'
        run: |
          echo "**** 1 ****"
          pwd
          echo "**** 2 ****"
          ls
          echo  "**** 3 ****"
          cd ../
          echo  "**** 4 ****"
          ls
          echo "This step will be skipped on Monday and Thursday"
          python run.py
        continue-on-error: true

      - name: Running .py Every time
        run: |
          echo "This step will always run"
          python run.py
        continue-on-error: true